CREATE TABLE consumo_energia (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa VARCHAR2(100),
    consumo_kw NUMBER(10,2),
    data_registro TIMESTAMP,
    alerta_gerado CHAR(1)
);

CREATE TABLE alerta (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo VARCHAR2(50),
    descricao VARCHAR2(255),
    data TIMESTAMP
);